# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# DataSource
spring.datasource.url=jdbc:h2:mem:coursedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# JWT Secret Key
jwt.secret=TXlTZWNyZXRLZXlGb3JDb3Vyc2VQbGF0Zm9ybV9BbmRTb21lUmFuZG9tTnVtYmVyc181NDMyMSE=